'''
Author: JunQiLiu
Date: 2021-09-07 12:47:01
LastEditTime: 2022-01-06 12:30:46
Description: 
FilePath: \stm32f401ccu6_rtthread\applications\SConscript

'''
import rtconfig
from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd, str(Dir('#'))]
src     = Split("""
main.c
modbus_slave_app.c
adc_app.c
fal_flash_stm32f4_port.c 
i2c_app.c
""")

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
